# Generated by Django 2.2 on 2019-05-23 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_delete_customuser'),
        ('users', '0005_auto_20190523_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Group_zero', to='smart.Group'),
        ),
    ]
