# Generated by Django 2.2 on 2019-05-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name', 'device')},
        ),
    ]
