# Generated by Django 2.2 on 2019-05-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
