# Generated by Django 2.2 on 2019-04-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(to='smart.Channel'),
        ),
    ]
