# Generated by Django 2.2 on 2019-04-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username', 'email']},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='smartDevices',
            new_name='group',
        ),
    ]
