# Generated by Django 2.2 on 2019-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='smart.Channel', verbose_name='permissions'),
        ),
    ]
