# Generated by Django 2.2 on 2019-05-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_auto_20190528_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
