# Generated by Django 2.2 on 2019-04-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_auto_20190412_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='permissions', to='smart.Channel'),
        ),
    ]
